import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { getWorkspaceRoot, setWorkspaceRoot } from '../core/paths.mjs';
import { listWorkspaceReferences } from '../core/workspace-reference-files.mjs';

test('reference search flattens nested files, excludes toolchain dependencies and stays in the active workspace', async t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'mli-reference-search-'));
  const previous = getWorkspaceRoot(), root = path.join(directory, 'project');
  t.after(() => { setWorkspaceRoot(previous); fs.rmSync(directory, { recursive: true, force: true }); });
  const write = (relative, text = 'body') => { const file = path.join(root, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); };
  for (const relative of ['docs/deep/文稿.md', 'docs/文稿.md', 'python/main.py', 'java/Main.java', 'go/main.go', 'rust/main.rs', 'src/Program.cs', 'lib/main.dart', 'sources/App.swift']) write(relative);
  const dependencies = ['node_modules', 'node_models', '.venv', '__pycache__', 'site-packages', '.gradle', '.m2', '.cargo', 'target', 'obj', '.nuget', '.dart_tool', '.pub-cache', 'Pods', 'Carthage', '.swiftpm', 'vendor', '.bundle', 'pkg/mod'];
  for (const dep of dependencies) write(`${dep}/nested/依赖.md`);
  write('python-runtime/pyvenv.cfg'); write('python-runtime/依赖.md');
  write('conda-runtime/conda-meta/package.json'); write('conda-runtime/依赖.md');
  write('.agent/private.md'); write('.git/internal.md');
  const outside = path.join(directory, 'outside'); fs.mkdirSync(outside); fs.writeFileSync(path.join(outside, 'external.md'), 'outside');
  fs.symlinkSync(outside, path.join(root, 'linked'), process.platform === 'win32' ? 'junction' : 'dir');
  for (let i = 0; i < 230; i++) write(`many/file-${i}.txt`);
  setWorkspaceRoot(root);
  const all = await listWorkspaceReferences({ limit: 200 });
  assert.equal(all.workspace, root);
  assert.equal(all.entries.length, 200);
  assert.equal(all.hasMore, true);
  assert.equal(all.incomplete, false);
  assert.equal((await listWorkspaceReferences({ query: '依赖' })).entries.length, 0);
  assert.equal((await listWorkspaceReferences({ query: 'external' })).entries.length, 0);
  assert.equal((await listWorkspaceReferences({ query: 'private' })).entries.length, 0);
  const nested = await listWorkspaceReferences({ query: 'docs\\deep 文稿' });
  assert.deepEqual(nested.entries.map(item => item.path), ['docs/deep/文稿.md']);
  assert.equal((await listWorkspaceReferences({ query: 'docs/deep' })).entries.some(item => item.path === 'docs/deep' && item.type === 'directory'), true);
  assert.equal((await listWorkspaceReferences({ query: 'many/file-229' })).entries.length, 1, 'search must include files beyond the default result page');
  for (const relative of ['python/main.py', 'java/Main.java', 'go/main.go', 'rust/main.rs', 'src/Program.cs', 'lib/main.dart', 'sources/App.swift']) assert.equal((await listWorkspaceReferences({ query: relative })).entries.length, 1);
  setWorkspaceRoot(path.join(directory, 'second-project'));
  assert.deepEqual((await listWorkspaceReferences()).entries, [], 'cached results cannot cross workspaces');
});
