import { confirmAction } from './ActionPopover.jsx';
import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, Check, ChevronRight, Download, Package, Pencil, Plus, RefreshCw, Search, Server, Sparkles, Trash2, Wrench, X } from 'lucide-react';
import './expert-library.css';

const request = async (url, options = {}) => {
  const response = await fetch(url, { ...options, headers: { 'content-type': 'application/json' }, body: options.body ? JSON.stringify(options.body) : undefined });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
  return data;
};
function skillKey(item) { return item.path || item.id || item.name; }

export default function ExpertSkillLibrary({ info, current, pending, running, onApply, onClear, onRefresh }) {
  const [tab, setTab] = useState('experts'), [pluginTab, setPluginTab] = useState('installed'), [query, setQuery] = useState(''), [selected, setSelected] = useState(null), [draft, setDraft] = useState(null), [error, setError] = useState(''), [remotePlugins, setRemotePlugins] = useState([]), [pluginBusy, setPluginBusy] = useState(false);
  const [saved, setSaved] = useState(() => { try { return JSON.parse(localStorage.getItem('mli-library-saved') || '{}'); } catch { return {}; } });
  const experts = info?.experts || [], plugins = info?.plugins?.plugins || [];
  useEffect(() => {
    let active = true;
    request('/api/account/plugins').then((data) => { if (active) setRemotePlugins(data.plugins || []); }).catch(() => { if (active) setRemotePlugins([]); });
    return () => { active = false; };
  }, []);
  const allSkills = useMemo(() => { const items = [...(info?.localSkills || []), ...(info?.plugins?.skills || [])]; return items.filter((item, index) => items.findIndex((other) => skillKey(other) === skillKey(item)) === index); }, [info]);
  const pluginCards = useMemo(() => plugins.map((plugin) => ({ ...plugin, kind: 'plugin', skills: allSkills.filter((skill) => skill.plugin === plugin.name || skill.path?.toLowerCase().includes(`plugins\\${plugin.name.toLowerCase()}\\`) || skill.path?.toLowerCase().includes(`plugins/${plugin.name.toLowerCase()}/`)) })), [plugins, allSkills]);
  const platformSkills = allSkills.filter((item) => item.source === 'platform'), mineSkills = allSkills.filter((item) => item.local || item.source === 'workspace' || (item.source === 'platform' && saved[`skill:${skillKey(item)}`]));
  const sourceLabel = (item, kind) => kind === 'expert' ? (item.local ? '我的专家' : item.platform ? '平台专家' : '专家') : item.source === 'plugin' ? `插件 · ${item.plugin || '已加载'}` : (item.local || item.source === 'workspace' ? '我的 Skill' : '平台 Skill');
  const items = tab === 'experts' ? experts.map((item) => ({ ...item, kind: 'expert' })) : tab === 'skills' ? platformSkills.map((item) => ({ ...item, kind: 'skill' })) : tab === 'mine' ? [...experts.filter((item) => item.local || saved[`expert:${item.id}`]).map((item) => ({ ...item, kind: 'expert' })), ...mineSkills.map((item) => ({ ...item, kind: 'skill' }))] : [];
  const displayed = items.filter((item) => `${item.name} ${item.description || ''} ${item.category || ''} ${item.plugin || ''}`.toLowerCase().includes(query.trim().toLowerCase()));
  const installedNames = new Set(plugins.map((item) => item.name));
  const displayedPlugins = pluginCards.filter((item) => `${item.name} ${item.description || ''} ${(item.tools || []).join(' ')} ${(item.skills || []).map((skill) => skill.name).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
  const displayedRemotePlugins = remotePlugins.filter((item) => `${item.name} ${item.description || ''} ${item.author || ''}`.toLowerCase().includes(query.trim().toLowerCase()));
  const activeExpertId = current?.expertId || pending?.id || '';
  function setTabAndClear(value) { setTab(value); setSelected(null); setError(''); }
  function toggleSaved(kind, item) { const key = `${kind}:${kind === 'expert' ? item.id : skillKey(item)}`, next = { ...saved, [key]: !saved[key] }; setSaved(next); localStorage.setItem('mli-library-saved', JSON.stringify(next)); }
  function startDraft(kind, item = null) { setError(''); setDraft(item ? { ...item, kind } : kind === 'expert' ? { kind, name: '', description: '', category: '自建', tags: [], prompt: '' } : { kind, name: '', description: '', content: '' }); }
  async function saveItem() { try { await request(`/api/library/${draft.kind === 'expert' ? 'experts' : 'skills'}`, { method: 'POST', body: draft }); setDraft(null); setError(''); await onRefresh(); } catch (reason) { setError(reason.message); } }
  async function removeItem(item, kind) { if (!await confirmAction(`删除“${item.name}”？`)) return; try { await request(`/api/library/${kind === 'expert' ? 'experts' : 'skills'}/${item.id}`, { method: 'DELETE' }); setSelected(null); setError(''); await onRefresh(); } catch (reason) { setError(reason.message); } }
  async function installPlugin(item) { setPluginBusy(true); setError(''); try { await request(`/api/account/plugins/${encodeURIComponent(item.id)}/install`, { method: 'POST', body: { sha256: item.sha256 } }); await request('/api/plugins/reload', { method: 'POST' }); await onRefresh(); setPluginTab('installed'); } catch (reason) { setError(reason.message); } finally { setPluginBusy(false); } }
  return <div className="collection-page library-hub">
    <header className="collection-header library-hub-head"><div><h1>专家与 Skill</h1><p>专家负责当前会话的工作方式，Skill 按需提供可复用流程；插件运行时能力在“已加载插件”中管理。</p></div><label className="collection-search"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索名称或描述"/></label></header>
    <div className="library-hub-tabs" role="tablist"><button role="tab" aria-selected={tab === 'experts'} className={tab === 'experts' ? 'active' : ''} onClick={() => setTabAndClear('experts')}><Sparkles size={16}/>专家 <small>{experts.length}</small></button><button role="tab" aria-selected={tab === 'skills'} className={tab === 'skills' ? 'active' : ''} onClick={() => setTabAndClear('skills')}><Wrench size={16}/>Skill 库 <small>{platformSkills.length}</small></button><button role="tab" aria-selected={tab === 'plugins'} className={tab === 'plugins' ? 'active' : ''} onClick={() => setTabAndClear('plugins')}><Package size={16}/>插件 <small>{plugins.length + remotePlugins.filter((item) => !installedNames.has(item.packageName)).length}</small></button><button role="tab" aria-selected={tab === 'mine'} className={tab === 'mine' ? 'active' : ''} onClick={() => setTabAndClear('mine')}><BookOpen size={16}/>我的 <small>{mineSkills.length + experts.filter((item) => item.local || saved[`expert:${item.id}`]).length}</small></button></div>
    <div className="library-hub-actions"><span>{tab === 'experts' ? '一次只能引用一位专家；选择后会在当前工作目录自动新建会话。' : tab === 'skills' ? '平台 Skill 由 Agent 按需读取，不会自动塞进每轮上下文。' : tab === 'plugins' ? '插件包由后台统一发布，安装后由本地 Agent 执行。' : '我的内容保存在本机。'}</span>{tab !== 'plugins' && <><button onClick={() => startDraft('expert')}><Plus size={15}/>添加专家</button><button onClick={() => startDraft('skill')}><Plus size={15}/>添加 Skill</button></>}</div>
    {error && <p className="library-error">{error}</p>}
    <div className="library-hub-grid">{displayed.map((item) => { const kind = item.kind, key = kind === 'expert' ? item.id : skillKey(item), active = kind === 'expert' && activeExpertId === item.id, isSaved = saved[`${kind}:${key}`]; return <article className={`library-hub-card ${active ? 'is-active' : ''}`} key={`${kind}:${key}`}><button className="library-card-body" onClick={() => setSelected(item)}><span className={`library-card-icon ${kind}`}>{kind === 'expert' ? <Sparkles size={18}/> : <Wrench size={18}/>}</span><span><b>{item.name}</b><small>{item.category || sourceLabel(item, kind)}</small></span><ChevronRight size={16}/></button><p>{item.description || (kind === 'skill' ? '可复用的工作流程 Skill' : '当前会话的专家提示词')}</p><div className="library-card-foot"><span>{sourceLabel(item, kind)}</span>{active && <span className="library-active"><Check size={13}/>当前引用 <button className="library-clear" title="取消引用专家" aria-label="取消引用专家" onClick={(event) => { event.stopPropagation(); onClear?.(); }}><X size={13}/></button></span>}{tab !== 'experts' && !item.local && <button onClick={(event) => { event.stopPropagation(); toggleSaved(kind, item); }} title={isSaved ? '从我的内容移除' : '添加到我的内容'}>{isSaved ? <Check size={16}/> : <Plus size={16}/>}</button>}</div></article>; })}</div>
    {tab === 'plugins' && <section className="library-plugin-section"><header><div><h2>{pluginTab === 'installed' ? '已安装插件' : '后端插件仓库'}</h2><p>{pluginTab === 'installed' ? '插件包来自后台仓库，工具仍在本地 Agent 中执行。' : '从后台发布的插件包安装到当前 Agent。'}</p></div><div className="library-plugin-tabs"><button className={pluginTab === 'installed' ? 'active' : ''} onClick={() => setPluginTab('installed')}>已安装 {plugins.length}</button><button className={pluginTab === 'remote' ? 'active' : ''} onClick={() => setPluginTab('remote')}><Server size={14}/>仓库 {remotePlugins.length}</button></div></header>{pluginTab === 'installed' ? <div className="library-plugin-grid">{displayedPlugins.map((plugin) => <button className="library-plugin-card" key={`plugin:${plugin.name}`} onClick={() => setSelected(plugin)}><span className="library-plugin-icon"><Package size={18}/></span><span><b>{plugin.name}</b><small>已安装 · 本地执行</small><em>{(plugin.tools || []).length} 个工具 · {(plugin.skills || []).length} 个 Skill · v{plugin.version || '-'}</em></span><ChevronRight size={16}/></button>)}</div> : <div className="library-plugin-grid">{displayedRemotePlugins.map((plugin) => <article className="library-plugin-card library-plugin-remote" key={`remote:${plugin.id}`}><span className="library-plugin-icon"><Server size={18}/></span><span><b>{plugin.name}</b><small>{plugin.description || '后台插件仓库'}</small><em>{plugin.author || '平台插件'} · v{plugin.version}</em></span>{installedNames.has(plugin.packageName) ? <span className="library-plugin-installed"><Check size={14}/>已安装</span> : <button disabled={pluginBusy} onClick={() => installPlugin(plugin)}><Download size={14}/>安装</button>}</article>)}</div>}{pluginTab === 'installed' && !displayedPlugins.length && <p className="library-plugin-empty">当前没有已加载插件</p>}{pluginTab === 'remote' && !displayedRemotePlugins.length && <p className="library-plugin-empty">没有可安装的后台插件，请先登录账户。</p>}</section>}
    {!displayed.length && !(tab === 'plugins' && displayedPlugins.length) && <div className="collection-empty"><BookOpen size={27}/><b>没有匹配的内容</b></div>}
    {selected && <div className="dialog-layer" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><section className="dialog-card wide library-detail" role="dialog" aria-modal="true" aria-label={selected.name}><header className="library-detail-head"><div><small className="library-detail-eyebrow">{selected.kind === 'plugin' ? '运行时插件' : selected.kind === 'expert' ? sourceLabel(selected, 'expert') : sourceLabel(selected, 'skill')}</small><h3>{selected.name}</h3><p>{selected.description || '暂无描述'}</p></div><button title="关闭" aria-label="关闭详情" onClick={() => setSelected(null)}><X size={17}/></button></header>{selected.kind === 'plugin' ? <div className="library-detail-body"><div className="plugin-detail-stats"><span><b>{(selected.tools || []).length}</b><small>工具</small></span><span><b>{(selected.skills || []).length}</b><small>Skill</small></span><span><b>{selected.version || '-'}</b><small>版本</small></span></div><h4>已注册工具</h4><div className="plugin-detail-tags">{(selected.tools || []).length ? selected.tools.map((tool) => <span key={tool}><Wrench size={12}/>{tool}</span>) : <small>此插件没有声明工具。</small>}</div><h4>随插件加载的 Skill</h4><div className="plugin-detail-skills">{(selected.skills || []).length ? selected.skills.map((skill) => <div key={skillKey(skill)}><b>{skill.name}</b><span>{skill.description || '插件本地 Skill'}</span></div>) : <small>此插件没有携带 Skill。</small>}</div></div> : <div className="library-detail-body"><div className="library-detail-meta"><span>{selected.kind === 'expert' ? '提示词文档' : '可复用流程'}</span>{selected.category && <span>{selected.category}</span>}</div><pre>{selected.kind === 'expert' ? selected.prompt : selected.content || '此 Skill 暂无可显示正文。'}</pre></div>}<footer className="dialog-actions">{selected.kind === 'plugin' && <button onClick={async () => { try { await request('/api/plugins/reload', { method: 'POST' }); await onRefresh?.(); setSelected(null); } catch (reason) { setError(reason.message); } }}><RefreshCw size={15}/>重新加载插件</button>}{selected.kind !== 'plugin' && selected.local && <><button onClick={() => { startDraft(selected.kind, selected); setSelected(null); }}><Pencil size={15}/>编辑</button><button onClick={() => removeItem(selected, selected.kind)}><Trash2 size={15}/>删除</button></>}{selected.kind === 'expert' && (activeExpertId === selected.id ? <button onClick={() => { onClear?.(); setSelected(null); }}><X size={15}/>取消引用</button> : <button className="primary-action" disabled={running} onClick={() => { onApply(selected); setSelected(null); }}>引用专家</button>)}</footer></section></div>}
    {draft && <div className="dialog-layer" onMouseDown={(event) => { if (event.target === event.currentTarget) setDraft(null); }}><section className="dialog-card wide library-editor" role="dialog" aria-modal="true" aria-label={draft.kind === 'expert' ? '编辑专家' : '编辑 Skill'}><header><h3>{draft.id ? '编辑' : '添加'}{draft.kind === 'expert' ? '专家' : ' Skill'}</h3><button title="关闭" onClick={() => setDraft(null)}><X size={17}/></button></header><div className="dialog-form"><label>名称<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><label>描述<input value={draft.description || ''} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/></label>{draft.kind === 'expert' && <><label>分类<input value={draft.category || ''} onChange={(event) => setDraft({ ...draft, category: event.target.value })}/></label><label>标签（逗号分隔）<input value={(draft.tags || []).join(', ')} onChange={(event) => setDraft({ ...draft, tags: event.target.value.split(',').map((tag) => tag.trim()).filter(Boolean) })}/></label></>}<label>{draft.kind === 'expert' ? '专家提示词' : 'Skill 内容'}<textarea rows={12} value={draft.kind === 'expert' ? draft.prompt : draft.content} onChange={(event) => setDraft({ ...draft, [draft.kind === 'expert' ? 'prompt' : 'content']: event.target.value })}/></label>{error && <p className="library-error">{error}</p>}<div className="dialog-actions"><button onClick={() => setDraft(null)}>取消</button><button className="primary-action" onClick={saveItem}>保存到本地</button></div></div></section></div>}
  </div>;
}
